package com.cooksys.friendlr.exception;

public class PetNotFoundException extends RuntimeException {

	/**
	 * Auto generated by eclipses
	 */
	private static final long serialVersionUID = -2192694110867228171L;

	public PetNotFoundException(Integer petId) {
		super("Pet not found for id[" + petId + "] !");
	}
}
